yfcc-10M:
    pgvector:
      docker-tag: neurips23-filter-pgvector
      module: neurips23.filter.pgvector.pgvector_index
      constructor: PgvectorIndex
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "FilterIVFFlatU8", "num_clusters": "2048", "precompute_intersection_threshold": "1600"}]
          query-args: |
            [
            {"fraction_coefficient": "13.0", "fraction_exponent": "0.65", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "12.0", "fraction_exponent": "0.65", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "11.5", "fraction_exponent": "0.65", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "11.0", "fraction_exponent": "0.65", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "10.5", "fraction_exponent": "0.65", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "10.5", "fraction_exponent": "0.64", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "10.0", "fraction_exponent": "0.64", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "9.5", "fraction_exponent": "0.64", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "9.0", "fraction_exponent": "0.64", "skip_clustering_threshold": 2000},
            {"fraction_coefficient": "8.5", "fraction_exponent": "0.64", "skip_clustering_threshold": 2000}
            ]
